### ISSUE TITLE
Refer button not showing when you filter started tests

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#197]

**Comment by mapesa** [comment]
By defination, we can't refer a specimen **after**  its corresponding test has **started**. We only show the refer button under the following conditions:

1. the corresponding test has been received 
1. the test **has not** been started.
1. the specimen **is not** already referred
1. the test **is not** an *external* test
1. the logged in user has rights to refer a specimen

As a matter of fact, under the following conditions, **none** of the tests coming from Sanitas can be referred because their `tests.external_id` is always set.

If this logic is flawed please highlight the right one then we can make ammends.

**Comment by briankip** [comment]
Aaaahhh  I see then the problem is if a test is external, and you accept it, it shows the refer button(ajax). But if you refer it disappears, the button shouldn't actually show but it shows. Minor issue though.
