### ISSUE TITLE
UI is not intuitive

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#257]
We need to simplify a lot of things, the process of adding a patient and then adding a test is too convoluted. We need to simplify it.

**Comment by mapesa** [comment]
Any concrete suggestions?

How do they do it on Sanitas? I bet its equally if not more complicated.
(Even creating a new Gmail contact is more complicated than our 3 step
process).

The only optimization that occurs to me right now is that we can *add a "**New
Patient" button on the patient search dialog* launched by the "New Test"
button.

**Comment by kitsao** [comment]
In the previous BLIS, 'New Patient' catered for both patient details and tests ordered. If we could do it as it was then, I think it will be a lot easier.

**Comment by ereng** [comment]
I think the many dialogs in the old-blis made the work process so very simple (the user could feel the flow you know?) especially the testing process - so turn these to dialogs?
 - enter results
 - edit
 - view details
 	- view report(open on another tab?)
 	- with OK or CLOSE or X (like am done!) - instead of the back button
 - verify (which is really view details above)
 	- view report(open on another tab?)
 	- with OK or CLOSE or X (like am done!) - instead of the back button
 - reject
 - refer sample

Update the index buttons with ajax
This should sort out the issue: I can't find the test am working on!

**Comment by briankip** [comment]
That new test button is the one that is confusing, i suggest we remove it and move the operations to the patients page. 
* You add a patient.
* On redirect to the patients page the new test button should be with view, edit, delete.
* Remove the measures panel and add a search text-box where you can type the test and it appears.
