### ISSUE TITLE
Report bugs

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#268]
Look for all report bugs and document them here, then fix them.

**Comment by Piusyo** [comment]
Provisional results on the reports bugs

Patient report
1.When you view the reports of some patients, it throws an error `{Trying to get property of non-object (View: C:\xampp\htdocs\BLIS\app\views\reports\patient\report.blade.php)} e.g 38137`
2.Returns Zero specimen records for all patients!

Daily log
1.The interface Seems complex
2. Zero data displayed

Prevalence Rates
1.Returns Zero information

Counts
1.Returns Zero information

Turnaround Time
1.Labeling `massages.Daily` instead of `Daily`

Infection Report
1.Returns Zero information

The user statistics report
1.Taking too long load!
2.When you filter using patient registry, it throws an error`{(SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_by' in 'where clause' (SQL: select `id` from `patients` where `patients`.`deleted_at` is null and `created_at` between 2014-02-17 and 2015-02-17 23:59:59 and `created_by` = 26)}`

NB
1.It is logical to add a print button on the reports?
2.The export button exports empty reports

**Comment by Piusyo** [comment]
The user statistics report

3. When you filter using tests registry an error is thrown `DataTables warning: table Id= DataTables_Table_0-requested unknown parameter '1' for row 0.`

**Comment by Piusyo** [comment]
A search using patient name in both patient and patient report returns zero results

**Comment by briankip** [comment]
Have you imported the data?

**Comment by Piusyo** [comment]
Findings on the reports,
The report are taking too long to load, other are at points failing to load.
