### ISSUE TITLE
in-patient outpatient confusion

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#281]
@piusyo have you finished?? See where the problem is and fix it, and write a test to fix it.

**Comment by Piusyo** [comment]
Investigation in progress.

**Comment by Piusyo** [comment]
@briankip 
The interaction between the visit and external_dump tables seems fine and the conversion of the `ip` to `In-Patient` and `op` to `Out-Patient`.
Primarily, I found that some visists have been created before external lab request- I couldnt get the logic but I believe there is or its simply fault... shouldnt it be the opposite? 
The cause could be when creating lab request for patients who had a lab request earlier via same system or had visited before.

Conclusion
The problem is there and its real. I have exhusted much on the it but I couldnt find its source, but I believe its patient related.
It needs someone with a deeper understanding of the system and how different processes are interconnected.

Kindly have a look at it.
